#!/usr/bin/env bash
#
# verify-build.sh — Phase 7 of the install-pendo-mobile skill.
#
# Proves the app still compiles after the Pendo Mobile SDK install. Discovers
# the project layout with each platform's own tooling (xcodebuild -list,
# gradlew, expo config, dotnet) rather than guessing from file naming
# conventions, resolves dependencies before building (a build that fails
# only because deps were never fetched is a false negative), and never
# requires code signing.
#
# Usage: verify-build.sh <ios|android|react-native|expo|flutter|maui>
#
# Run it from the APP ROOT, which in a monorepo is not the git root — see
# "Working-directory contract" below.
#
# Exit codes:
#   0  build succeeded
#   1  build failed, and the failure is attributable to this install
#   2  not verified — a required toolchain is absent, the script was run
#      from the wrong directory, or the build failed with no mention of
#      Pendo anywhere in the failing step's own output, so the failure
#      cannot be attributed to this install. Not a failure — but also not a
#      silent pass: this script always prints an "Android head:"/"iOS head:"
#      line naming the specific reason, and callers must surface that line
#      rather than collapsing it into a bare PASS/FAIL word.
#
# Cross-platform frameworks (react-native, expo, flutter) ship two native
# heads (ios/, android/). Each head function reports its own 0/1/2, and
# record_head() turns that into exactly one "<Label> head:" line. A head
# excluded from the verdict (toolchain absent, or an unattributable failure
# — see head_verdict() below) is logged and excluded rather than counted as
# a failure; the overall result is FAIL if any attempted-and-attributable
# head failed, "not verified" (2) only if *no* head could be verified at
# all, and PASS otherwise. This is what lets "no Xcode here", a modern
# Expo/New-Architecture app whose iOS build fails inside Expo's own
# precompiled module maps, and a React Native repo whose Android build was
# already broken before Pendo arrived, all stay true no-ops instead of false
# failures — while a genuinely Pendo-caused failure on either head (one whose
# output does mention Pendo) still reports FAIL.
#
# Expo: a managed project has no ios/ or android/ directory until `expo
# prebuild` generates them. This script prebuilds (rather than stopping at
# `expo config` validation) so a broken config-plugin output is actually
# caught — validating config alone is cheaper but would let a broken plugin
# output pass as a "successful build" — and then deletes exactly the
# directories it generated. The cleanup is not tidiness: managed Expo
# templates gitignore /ios and /android, so directories left behind survive
# `git checkout` and `git reset --hard`, and the next run of this skill then
# reads a managed repo as `prebuilt` (SKILL.md Phase 1) and reads the
# plugin-generated PendoGateActivity as proof of an existing install
# (SKILL.md Phase 3), hard-stopping on source that contains zero Pendo.
# Only directories this run created are removed — a prebuilt repo's
# committed ios/ and android/ are never touched. See cross_platform_js_build().
set -u
set -o pipefail

# Native directories generated by this run (managed Expo only), removed again
# before it returns. Empty for every other platform and for prebuilt Expo.
GENERATED_NATIVE_DIRS=""

usage() {
  echo "usage: $(basename "$0") <ios|android|react-native|expo|flutter|maui>" >&2
}

log() { echo "[verify-build] $*"; }
err() { echo "[verify-build] $*" >&2; }

if [ "$#" -eq 0 ]; then
  usage
  exit 1
fi

PLATFORM="$1"

# ---------------------------------------------------------------------------
# Shared discovery helpers
# ---------------------------------------------------------------------------

find_first() {
  # find_first <glob-name> <search-root>
  # First filesystem match, pruning common vendor/build directories so we
  # don't pick up e.g. Pods/Pods.xcodeproj or a stale build/ output instead
  # of the real project. Also prunes everything *inside* a `.xcodeproj`
  # bundle — notably its internal `project.xcworkspace`, which every
  # `.xcodeproj` carries as its own single-project bookkeeping workspace.
  # Without this prune, searching for `*.xcworkspace` can match that
  # internal one instead of a real top-level, CocoaPods-generated
  # `<App>.xcworkspace` sitting right next to it: `xcodebuild` happily
  # builds the internal workspace, but it only knows about the one project
  # inside it, not the separate `Pods.xcodeproj` a top-level workspace
  # would also reference — so the Pods target, and everything the install
  # depends on via CocoaPods, silently never gets built. Confirmed against
  # a real CocoaPods-tier iOS install: `find` returned
  # `Avocados.xcodeproj/project.xcworkspace` ahead of the real
  # `Avocados.xcworkspace`, and building it failed with `framework
  # 'Pods_Avocados' not found`. No -maxdepth guess: real repos nest native
  # projects at varying depths, so we prune noise instead of capping depth.
  find "$2" \
    \( -path '*/node_modules' -o -path '*/Pods' -o -path '*/.git' \
       -o -path '*/DerivedData' -o -path '*/build' -o -path '*/.build' \
       -o -path '*/Carthage' -o -path '*.xcodeproj/*' \) -prune \
    -o -iname "$1" -print 2>/dev/null | head -n 1
}

pick_scheme() {
  # $1 = captured `xcodebuild -list` output, $2 = project/workspace
  # basename with no extension. Prefers a scheme matching that name (the
  # common "MyApp.xcodeproj -> MyApp scheme" convention); falls back to the
  # first scheme xcodebuild reports so an unusually-named project still
  # gets *a* scheme rather than none.
  local list="$1" want="$2" schemes scheme
  schemes=$(printf '%s\n' "$list" | awk '
    /Schemes:/ { f = 1; next }
    f { if (!NF) exit; sub(/^[ \t]+/, ""); print }
  ')
  scheme=$(printf '%s\n' "$schemes" | grep -Fx "$want" | head -n 1)
  if [ -z "$scheme" ]; then
    scheme=$(printf '%s\n' "$schemes" | head -n 1)
  fi
  printf '%s\n' "$scheme"
}

# ---------------------------------------------------------------------------
# Shared failure attribution — used by every native head on every platform.
# ---------------------------------------------------------------------------

# A failed build is only attributable to this install if Pendo is actually
# mentioned somewhere in the output of the specific step that failed. This
# applies to every head on every platform, not just iOS: pre-existing
# breakage in a repo the install never touched has been reproduced on
# verified Pendo-free trees on both heads — a dead `compile()` Gradle DSL in
# a third-party React Native module, a react-native-worklets CMake ordering
# failure, a Gradle/JDK class-file version mismatch on Flutter, and (the
# original iOS case, reproduced 3x with clean DerivedData on an Expo SDK 57
# / New Architecture app) failures inside Expo's own precompiled module maps
# with zero Pendo mentions. Returning 1 for any of those tells the developer
# this install broke their app when the evidence says it never touched the
# failure.
#
# Deliberately scoped to *the failing step's own output* rather than
# everything captured so far in the same run: a successful `pod install`
# almost always lists "Pendo (x.y.z)" among the installed pods, so checking
# a cumulative log would make every later, unrelated failure look
# "Pendo-attributable" by coincidence.
#
# $1 = head label for the message ("Android", "iOS", "Flutter Android", …).
# $2 = captured stdout+stderr of the step that just failed.
head_verdict() {
  local head="$1" output="$2"

  if [ -z "$output" ]; then
    # Nothing captured to inspect — err on the side of caution and report a
    # real failure rather than guessing.
    return 1
  fi

  if printf '%s\n' "$output" | grep -qi 'pendo'; then
    return 1
  fi

  err "${head} build failed, but nothing in this step's own output mentions Pendo — treating this as unverifiable rather than attributing it to the Pendo install (see the errors above)"
  return 2
}

# Runs one build step, attributing any failure via head_verdict(). Output is
# captured rather than streamed so it can be inspected before the verdict.
# Returns 0, or head_verdict's 1 (attributable) / 2 (not).
attributed_step() {
  local head="$1" description="$2"
  shift 2
  local output rc

  log "$description"
  output=$("$@" 2>&1)
  rc=$?
  printf '%s\n' "$output"
  [ "$rc" -eq 0 ] && return 0

  err "failed: ${description}"
  head_verdict "$head" "$output"
}

# Folds one native head's 0/1/2 into the running tally and prints the
# "<Label> head:" line SKILL.md Phase 7 requires for every head of every
# dual-head platform — the line is emitted here, once, so no head can be
# built without one. Reads and updates the caller's `heads`/`fails` locals:
# bash has no by-reference return, and threading two counters back through
# stdout would be worse than relying on the one dynamic scope both callers
# already establish.
record_head() {
  local label="$1" rc="$2"

  case "$rc" in
    0) log "${label} head: verified — build succeeded"; heads=$((heads + 1)) ;;
    2) log "${label} head: not verified — not counted against the verdict (required toolchain absent, or a build failure that could not be attributed to Pendo — see reason above)" ;;
    *) log "${label} head: FAILED — see errors above"; heads=$((heads + 1)); fails=$((fails + 1)) ;;
  esac
}

# ---------------------------------------------------------------------------
# Working-directory contract
# ---------------------------------------------------------------------------
#
# Every head below probes ios/ and android/ relative to the current
# directory and resolves JS/Dart dependencies there, so the contract is "run
# me from the app root" — which in a monorepo is *not* the git root. The git
# root is exactly where a caller is likely to be standing, since SKILL.md's
# Phase 0 (git status) and Phase 5 (git checkout -b) both run there.
# Undetected, that produces a bare "nothing could be verified" which reads as
# "this repo has no native heads" rather than "you are looking in the wrong
# place". Observed on a real Flutter pub workspace whose app lives at
# compass_app/app.
#
# Both outcomes stay exit 2 ("not verified"): nothing was built either way,
# and neither is a failure attributable to the install. Only the message
# differs — and the wrong-directory one names where to re-run.

# The file marking a candidate app root. `ios` and `maui` have no entry on
# purpose: their discovery (find_first, find_maui_head_project) already
# searches recursively from the current directory, so a monorepo root works
# for them unchanged.
platform_manifest() {
  case "$1" in
    react-native|expo) echo "package.json" ;;
    flutter)           echo "pubspec.yaml" ;;
    android)           echo "gradlew" ;;
  esac
}

# Is there anything for this platform to build in directory $1? Deliberately
# stricter than "the manifest exists": a Dart pub workspace root carries a
# pubspec.yaml with no app under it, and a JS monorepo root carries a
# package.json with no native heads — which is exactly how the wrong
# directory sails through a naive manifest check.
is_buildable_dir() {
  local d="$1"

  case "$PLATFORM" in
    react-native)
      [ -f "$d/package.json" ] && { [ -d "$d/ios" ] || [ -d "$d/android" ]; }
      ;;
    expo)
      # A managed Expo app has neither ios/ nor android/ until prebuild —
      # that is what managed means — so a resolvable Expo config counts too.
      [ -f "$d/package.json" ] && {
        [ -d "$d/ios" ] || [ -d "$d/android" ] || [ -f "$d/app.json" ] ||
          ls "$d"/app.config.* >/dev/null 2>&1
      }
      ;;
    flutter)
      [ -f "$d/pubspec.yaml" ] && { [ -d "$d/ios" ] || [ -d "$d/android" ]; }
      ;;
    android)
      [ -f "$d/gradlew" ] || [ -f "$d/android/gradlew" ]
      ;;
    *)
      return 0
      ;;
  esac
}

require_buildable_cwd() {
  local manifest candidates dir
  manifest=$(platform_manifest "$PLATFORM")

  # ios/maui, and any unknown platform, opt out — nothing to assert.
  [ -n "$manifest" ] || return 0
  is_buildable_dir "." && return 0

  candidates=$(find . \
    \( -path '*/node_modules' -o -path '*/Pods' -o -path '*/.git' \
       -o -path '*/DerivedData' -o -path '*/build' -o -path '*/.build' \
       -o -path '*/Carthage' -o -path '*.xcodeproj/*' \) -prune \
    -o -name "$manifest" -print 2>/dev/null |
    while IFS= read -r hit; do
      dir=$(dirname "$hit")
      [ "$dir" = "." ] && continue
      is_buildable_dir "$dir" && printf '%s\n' "$dir"
    done | head -n 5)

  if [ -n "$candidates" ]; then
    err "wrong directory — nothing for platform \"${PLATFORM}\" to build in $(pwd)"
    err "This script runs from the app root; in a monorepo that is not the git root."
    err "Found ${PLATFORM} app root(s) below here:"
    printf '%s\n' "$candidates" | while IFS= read -r dir; do err "    ${dir}"; done
    err "Re-run from one of those directories."
    return 2
  fi

  err "no ${PLATFORM} app root found in $(pwd) or below it (looked for ${manifest} alongside a native head)"
  return 2
}

# ---------------------------------------------------------------------------
# iOS head — used directly by the `ios` platform (root ".") and as one of
# react-native/expo's two native heads (root "ios").
# ---------------------------------------------------------------------------

ios_head() {
  local root="$1" ws proj target flag name list scheme rc output

  if ! command -v xcodebuild >/dev/null 2>&1; then
    err "xcodebuild not found (Xcode command line tools required)"
    return 2
  fi

  if [ -f "${root}/Podfile" ]; then
    if ! command -v pod >/dev/null 2>&1; then
      err "Podfile found under \"${root}\" but CocoaPods (pod) is not installed"
      return 2
    fi
    log "pod install (\"${root}\")"
    output=$(cd "${root}" && pod install 2>&1)
    rc=$?
    printf '%s\n' "$output"
    if [ "$rc" -ne 0 ]; then
      err "pod install failed in \"${root}\""
      head_verdict "iOS" "$output"
      return $?
    fi
  fi

  # find_first already excludes each `.xcodeproj`'s internal
  # `project.xcworkspace` (see its own comment) — what `ws` finds here, if
  # anything, is always a real top-level workspace: hand-authored, or the
  # one CocoaPods generates alongside the `.xcodeproj` on `pod install`
  # (which just ran above, if a Podfile was present). Prefer it over the
  # bare `.xcodeproj` whenever one exists — a CocoaPods-tier install has no
  # other way to see the Pods project's targets.
  ws=$(find_first '*.xcworkspace' "$root")
  proj=$(find_first '*.xcodeproj' "$root")

  if [ -n "$ws" ]; then
    target="$ws"
    flag="-workspace"
  elif [ -n "$proj" ]; then
    target="$proj"
    flag="-project"
  else
    err "no .xcworkspace or .xcodeproj found under \"${root}\""
    return 1
  fi

  name=$(basename "$target")
  name="${name%.*}"

  # `xcodebuild -list` resolves the SPM package graph as a side effect
  # before it enumerates schemes (confirmed against a real project: its
  # output starts with "Resolve Package Graph"), and it fails if that
  # resolution fails — so this one call covers both "SPM resolution" and
  # scheme discovery. A separate `-resolvePackageDependencies` call needs
  # `-scheme` to run against a workspace, which we don't have yet at this
  # point, so don't add a redundant, ordering-fragile second call here.
  log "resolving Swift Package dependencies and enumerating schemes for \"${target}\" (xcodebuild -list)"
  list=$(xcodebuild -list "$flag" "$target" 2>&1)
  rc=$?
  printf '%s\n' "$list"
  if [ "$rc" -ne 0 ]; then
    err "xcodebuild -list failed for \"${target}\" (dependency resolution or scheme enumeration)"
    head_verdict "iOS" "$list"
    return $?
  fi
  scheme=$(pick_scheme "$list" "$name")
  if [ -z "$scheme" ]; then
    err "no schemes reported by xcodebuild -list for \"${target}\""
    return 1
  fi

  log "building scheme \"${scheme}\" from \"${target}\" (unsigned, iOS Simulator destination)"
  output=$(xcodebuild "$flag" "$target" -scheme "$scheme" \
    -destination 'generic/platform=iOS Simulator' \
    CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO \
    build 2>&1)
  rc=$?
  printf '%s\n' "$output"
  if [ "$rc" -ne 0 ]; then
    head_verdict "iOS" "$output"
    return $?
  fi

  return 0
}

# ---------------------------------------------------------------------------
# Android/Gradle head — used directly by the `android` platform and as one
# of react-native/expo's two native heads (root "android").
# ---------------------------------------------------------------------------

find_android_root() {
  # Native Android repos put the wrapper at the repo root or under
  # android/; react-native/expo always use ./android and call gradle_head
  # directly with that root, so this finder is only used for the native
  # `android` platform.
  if [ -f "android/gradlew" ]; then
    echo "android"
  elif [ -f "./gradlew" ]; then
    echo "."
  fi
}

gradle_head() {
  local root="$1" gradlew="${1}/gradlew" rc output

  if [ ! -f "$gradlew" ]; then
    err "no gradlew found under \"${root}\""
    return 2
  fi
  [ -x "$gradlew" ] || chmod +x "$gradlew" 2>/dev/null

  # Same probe SKILL.md's Phase 1 uses to decide whether Phase 7 can even
  # run — reusing it here means a "toolchain absent" verdict is never a
  # guess this script invented independently.
  if ! "$gradlew" --version >/dev/null 2>&1; then
    err "\"${gradlew} --version\" failed — Gradle/Java toolchain is not usable here"
    return 2
  fi

  log "resolving dependencies and building the debug APK in \"${root}\" (./gradlew assembleDebug)"
  # Captured, not streamed, so a failure can be attributed before it is
  # reported — same reason and same rule as the iOS head. Without this the
  # Android head returns Gradle's raw exit code, and any pre-existing
  # breakage in the developer's own repo is reported as a Pendo-caused FAIL:
  # reproduced on a verified Pendo-free React Native tree, where a dead
  # `compile()` DSL in a third-party module produced "BUILD FAILED" with
  # exit 1 and zero Pendo content anywhere in the repo.
  output=$(cd "${root}" && ./gradlew assembleDebug 2>&1)
  rc=$?
  printf '%s\n' "$output"
  if [ "$rc" -ne 0 ]; then
    head_verdict "Android" "$output"
    return $?
  fi

  return 0
}

android_build() {
  local root
  root=$(find_android_root)
  if [ -z "$root" ]; then
    err "no gradlew found under . or ./android"
    return 2
  fi
  gradle_head "$root"
}

# ---------------------------------------------------------------------------
# JS dependency resolution — shared by react-native and expo.
# ---------------------------------------------------------------------------

resolve_js_deps() {
  if [ -f yarn.lock ]; then
    if ! command -v yarn >/dev/null 2>&1; then
      err "yarn.lock present but yarn is not installed"
      return 2
    fi
    log "yarn install (resolving JS dependencies)"
    yarn install || { err "yarn install failed"; return 1; }
  elif [ -f pnpm-lock.yaml ]; then
    if ! command -v pnpm >/dev/null 2>&1; then
      err "pnpm-lock.yaml present but pnpm is not installed"
      return 2
    fi
    log "pnpm install (resolving JS dependencies)"
    pnpm install || { err "pnpm install failed"; return 1; }
  else
    if ! command -v npm >/dev/null 2>&1; then
      err "npm is not installed"
      return 2
    fi
    log "npm install (resolving JS dependencies)"
    npm install || { err "npm install failed"; return 1; }
  fi
}

# ---------------------------------------------------------------------------
# react-native / expo — both are JS projects with (once native projects
# exist) two native heads. Aggregation rule: a head whose directory is
# absent, whose toolchain is unavailable, or whose build failed
# without ever mentioning Pendo (see head_verdict()) is logged and
# excluded from the verdict; FAIL if any attempted-and-attributable head
# failed; "not verified" (2) only if no head could be verified at all;
# otherwise PASS.
# ---------------------------------------------------------------------------

# Removes only the native directories this run generated (see
# GENERATED_NATIVE_DIRS), restoring a managed Expo repo to the shape it had
# before verification. Never touches a prebuilt repo's committed ios/ and android/,
# because nothing is ever added to that list for one.
remove_generated_native_dirs() {
  local dir
  for dir in $GENERATED_NATIVE_DIRS; do
    [ -d "$dir" ] || continue
    log "removing ./${dir} — generated by this verification run, not part of the repo"
    rm -rf "./${dir}"
  done
  GENERATED_NATIVE_DIRS=""
}

cross_platform_js_build() {
  local flavor="$1" rc heads=0 fails=0

  GENERATED_NATIVE_DIRS=""

  if ! command -v node >/dev/null 2>&1; then
    err "node is not installed"
    return 2
  fi

  resolve_js_deps
  rc=$?
  [ "$rc" -eq 0 ] || return "$rc"

  if [ "$flavor" = "expo" ]; then
    if ! command -v npx >/dev/null 2>&1; then
      err "npx is not installed"
      return 2
    fi

    log "validating Expo config (npx expo config)"
    if ! npx expo config >/dev/null; then
      err "npx expo config failed — app.json/app.config.* does not resolve"
      return 1
    fi

    if [ ! -d ios ] && [ ! -d android ]; then
      log "managed Expo project (no ios/ or android/) — generating native projects with npx expo prebuild to verify the config plugin's output; they are removed again when this run finishes"
      # --no-install: resolve_js_deps already fetched JS dependencies above.
      # Whatever prebuild creates is recorded before it runs, so a partial
      # failure is cleaned up too.
      GENERATED_NATIVE_DIRS="ios android"
      if ! npx expo prebuild --no-install; then
        err "npx expo prebuild failed"
        remove_generated_native_dirs
        return 1
      fi
    else
      log "ios/ and/or android/ already present (prebuilt/bare workflow) — building them directly instead of re-prebuilding; note that pod install below rewrites ios/Podfile.lock and the Xcode project, which are committed files in this repo"
    fi
  fi

  if [ -d android ]; then
    gradle_head "android"
    record_head "Android" "$?"
  else
    log "Android head: skipped — no android/ directory"
  fi

  if [ -d ios ]; then
    ios_head "ios"
    record_head "iOS" "$?"
  else
    log "iOS head: skipped — no ios/ directory"
  fi

  remove_generated_native_dirs

  if [ "$heads" -eq 0 ]; then
    err "neither native head (ios/, android/) could be verified on this machine"
    return 2
  fi
  [ "$fails" -eq 0 ]
}

# ---------------------------------------------------------------------------
# Flutter — same dual-head shape as react-native/expo, but Flutter drives
# both native builds through its own CLI rather than raw xcodebuild/gradlew.
# ---------------------------------------------------------------------------

# Flutter gets the same two guarantees the react-native/expo path has, and
# previously had neither: a per-head "<Label> head:" line for every head
# (SKILL.md Phase 7 promises one "always", and this function used to collapse
# a passing iOS head and a failing Android head into the single line
# "BUILD FAILED (flutter)"), and failure attribution, so a pre-existing
# breakage is not reported as Pendo's doing. The pub-get and analyze gates
# run before either head and get attribution too — a repo whose analyzer was
# already red, or whose lockfile already did not resolve, is no more this
# install's fault than a failing native build is.
#
# Entry-point discovery below mirrors references/flutter.md's own enumeration
# exactly (same grep, same terminal/delegating split) so the two can't
# diverge: building only the default target — flutter.md's own "no build can
# catch a missed entry point" gap — is what let a flavored `--target` launch
# ship with Pendo never initialized while every build stayed green.

# Every top-level main() under lib/ — the same grep flutter.md tells the
# installing agent to run by hand.
flutter_entry_points() {
  grep -rlE '^(void|Future<void>) main\(' lib 2>/dev/null
}

# Terminal: its main() calls runApp() itself, so flutter.md requires a direct
# setup() call there — these are what this function builds, one per target.
# Delegating: main() only forwards to another entry point's main() (e.g.
# lib/main.dart's whole body is `development.main();`) and by design carries
# no setup() of its own — the terminal entry point it forwards to already
# covers that launch path, so it gets no separate build target either.
flutter_is_terminal_entry_point() {
  grep -q 'runApp(' "$1" 2>/dev/null
}

flutter_build() {
  local heads=0 fails=0 rc output
  local entry_points terminal_targets pendo_installed setup_call_sites target n suffix
  local has_android=0 has_ios=0

  if ! command -v flutter >/dev/null 2>&1; then
    err "flutter is not installed"
    return 2
  fi

  log "flutter pub get (resolving Dart package dependencies)"
  output=$(flutter pub get 2>&1)
  rc=$?
  printf '%s\n' "$output"
  if [ "$rc" -ne 0 ]; then
    err "flutter pub get failed"
    head_verdict "Flutter (pub get)" "$output"
    return $?
  fi

  log "flutter analyze (analyzer-error gate; pre-existing warnings do not fail this step)"
  output=$(flutter analyze 2>&1)
  rc=$?
  printf '%s\n' "$output"
  if [ "$rc" -ne 0 ]; then
    err "flutter analyze reported errors"
    head_verdict "Flutter (analyze)" "$output"
    return $?
  fi

  [ -d android ] && has_android=1
  [ -d ios ] && has_ios=1

  if [ "$has_android" -eq 0 ]; then
    log "Android head: skipped — no android/ directory"
  fi
  if [ "$has_ios" -eq 1 ] && ! command -v xcodebuild >/dev/null 2>&1; then
    log "iOS head: not verified — xcodebuild not available on this machine, not counted against the verdict"
    has_ios=0
  elif [ "$has_ios" -eq 0 ]; then
    log "iOS head: skipped — no ios/ directory"
  fi

  # Discover every terminal entry point so a flavor whose install missed
  # setup() gets its own build instead of riding along, uninitialized, under
  # the default target's green result. Falls back to the conventional
  # default target if entry points can't be enumerated at all — an
  # unconventional main() declaration flutter.md itself tells the installing
  # agent to loosen the pattern for; building nothing would be worse than
  # falling back to the one target every Flutter app has.
  entry_points=$(flutter_entry_points)
  terminal_targets=""
  if [ -n "$entry_points" ]; then
    while IFS= read -r target; do
      flutter_is_terminal_entry_point "$target" &&
        terminal_targets="${terminal_targets}${target}
"
    done <<<"$entry_points"
  fi
  [ -n "$terminal_targets" ] || terminal_targets="lib/main.dart
"

  n=$(printf '%s' "$terminal_targets" | grep -c .)
  if [ "$n" -gt 1 ]; then
    log "found ${n} terminal Flutter entry points under lib/ — building each with its own --target so a flavor whose install missed setup() fails visibly (this multiplies native build time by ${n}x; see references/flutter.md's entry-point enumeration)"
  fi

  # A missing setup() call compiles, so only a source check can catch it.
  # Skipped entirely on a Pendo-free tree, which has no setup() by definition.
  pendo_installed=0
  grep -qE '^[[:space:]]*pendo_sdk[[:space:]]*:' pubspec.yaml 2>/dev/null && pendo_installed=1

  setup_call_sites=""
  if [ "$pendo_installed" -eq 1 ]; then
    setup_call_sites=$(grep -rl 'PendoSDK\.setup(' lib 2>/dev/null | tr '\n' ' ')
  fi

  while IFS= read -r target; do
    [ -n "$target" ] || continue
    suffix=""
    [ "$n" -gt 1 ] && suffix=" (${target})"

    # A shared bootstrap holding the only setup() call is a shape
    # references/flutter.md permits, and a grep cannot resolve Dart imports to
    # prove this entry point reaches it — so only "absent everywhere" is a
    # provable miss and counts against the verdict.
    if [ "$pendo_installed" -eq 1 ] && ! grep -q 'PendoSDK\.setup(' "$target"; then
      if [ -z "$setup_call_sites" ]; then
        err "${target}: no PendoSDK.setup() call anywhere under lib/ — no launch path initializes Pendo"
        fails=$((fails + 1))
        heads=$((heads + 1))
      else
        err "${target}: setup() is not in this entry point but is in ${setup_call_sites}— correct if this path reaches it via a shared bootstrap, otherwise this flavor will not initialize Pendo. Not counted against the verdict; confirm by reading the call chain."
      fi
    fi

    if [ "$has_android" -eq 1 ]; then
      log "flutter build apk --debug --target ${target} (Android head${suffix})"
      output=$(flutter build apk --debug --target "$target" 2>&1)
      rc=$?
      printf '%s\n' "$output"
      if [ "$rc" -ne 0 ]; then
        err "flutter build apk --debug --target ${target} failed"
        head_verdict "Android${suffix}" "$output"
        rc=$?
      fi
      record_head "Android${suffix}" "$rc"
    fi

    if [ "$has_ios" -eq 1 ]; then
      log "flutter build ios --no-codesign --target ${target} (iOS head${suffix}, unsigned)"
      output=$(flutter build ios --no-codesign --target "$target" 2>&1)
      rc=$?
      printf '%s\n' "$output"
      if [ "$rc" -ne 0 ]; then
        err "flutter build ios --no-codesign --target ${target} failed"
        head_verdict "iOS${suffix}" "$output"
        rc=$?
      fi
      record_head "iOS${suffix}" "$rc"
    fi
  done <<<"$terminal_targets"

  if [ "$heads" -eq 0 ]; then
    err "neither Android nor iOS head could be built on this machine"
    return 2
  fi
  [ "$fails" -eq 0 ]
}

# ---------------------------------------------------------------------------
# MAUI
# ---------------------------------------------------------------------------

find_csproj_files() {
  find . \
    \( -path '*/bin' -o -path '*/obj' -o -path '*/node_modules' -o -path '*/.git' \) -prune \
    -o -iname '*.csproj' -print 2>/dev/null
}

declares_maui() {
  grep -qi '<UseMaui>[[:space:]]*true[[:space:]]*</UseMaui>' "$1" 2>/dev/null
}

# Matches Exe and WinExe, and tolerates the per-TFM Condition the MAUI
# template puts on this element.
declares_executable_output() {
  grep -qiE '<OutputType[^>]*>[[:space:]]*(Win)?Exe[[:space:]]*</OutputType>' "$1" 2>/dev/null
}

# The application head. Both markers are required because the MAUI class
# library template also sets UseMaui, which would otherwise make the head
# whichever .csproj `find` happened to return first.
find_maui_head_project() {
  find_csproj_files |
    while IFS= read -r proj; do
      declares_maui "$proj" && declares_executable_output "$proj" || continue
      printf '%s\n' "$proj"
      break
    done
}

msbuild_property() {
  dotnet msbuild "$1" -getProperty:"$2" 2>/dev/null
}

# `dotnet build -f` rejects any TFM the project does not declare (NETSDK1005),
# so this is read rather than assumed. MSBuild evaluation is preferred over the
# raw XML because it resolves conditions and Directory.Build.props.
maui_android_tfm() {
  local proj="$1" declared

  declared=$(msbuild_property "$proj" TargetFrameworks)
  [ -n "$declared" ] || declared=$(msbuild_property "$proj" TargetFramework)
  [ -n "$declared" ] || declared=$(cat "$proj" 2>/dev/null)

  printf '%s\n' "$declared" | tr ';' '\n' |
    grep -oE 'net[0-9]+\.[0-9]+-android[0-9.]*' | head -n 1
}

maui_build() {
  local proj tfm

  if ! command -v dotnet >/dev/null 2>&1; then
    err "dotnet is not installed"
    return 2
  fi

  proj=$(find_maui_head_project)
  if [ -z "$proj" ]; then
    err "no MAUI application head found (need a .csproj with both <UseMaui>true</UseMaui> and an executable <OutputType>)"
    return 2
  fi

  tfm=$(maui_android_tfm "$proj")
  if [ -z "$tfm" ]; then
    err "\"${proj}\" declares no Android target framework — this script verifies MAUI's Android head only"
    return 2
  fi

  attributed_step "MAUI" "dotnet restore \"${proj}\"" \
    dotnet restore "$proj" || return $?

  log "verifying the Android head only (${tfm}) — it needs no Xcode and no code signing; MAUI's iOS, MacCatalyst and Windows heads are not verified here"
  attributed_step "MAUI Android" "dotnet build \"${proj}\" -f ${tfm}" \
    dotnet build "$proj" -f "$tfm" -c Debug
}

# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------

# Assert the working-directory contract before anything runs, so a monorepo
# git root is told where the app is instead of being handed a bare "nothing
# could be verified". Opts out for ios/maui and for an unknown platform,
# which the case below still reports as usage error 1.
require_buildable_cwd
status=$?

if [ "$status" -eq 0 ]; then
  case "$PLATFORM" in
    ios)          ios_head "."; status=$? ;;
    android)      android_build; status=$? ;;
    react-native) cross_platform_js_build "react-native"; status=$? ;;
    expo)         cross_platform_js_build "expo"; status=$? ;;
    flutter)      flutter_build; status=$? ;;
    maui)         maui_build; status=$? ;;
    *)
      err "unknown platform: ${PLATFORM}"
      usage
      status=1
      ;;
  esac
fi

case "$status" in
  0) log "BUILD PASSED (${PLATFORM})" ;;
  2) log "BUILD NOT VERIFIED (${PLATFORM}) — see the detail above (required toolchain absent, wrong working directory, or a failure that could not be attributed to this install)" ;;
  *) err "BUILD FAILED (${PLATFORM})" ;;
esac

exit "$status"
